```{r, echo=FALSE, message=FALSE, warning=FALSE}
source(file = "include/deadlines.R")
```

# Course Overview {#Course_overview}

Welcome to your PSYCH5088 Research Methods 1 **`r study_year`** course on the MSc Psychology Conversion programme! We will introduce you to how psychologists use quantitative research methods to answer their research questions. There are many components that go into understanding and applying the techniques you will learn about, so throughout the semester we will cover fundamental research methods and statistics concepts, data skills to work with quantitative psychology data, and research skills to develop your understanding of reading and writing quantitative psychology reports. 

This book provides supporting information for the course such as the assignments you will complete and resources to support research and writing. Please take the time at the start of the course to read the following course overview and learn where your sources of support are. You will keep referring back to this book throughout the semester as you progress through the labs and you approach each assignment.

## Intended Learning Outcomes

By the end of the course, you will be able to:

- Understand and apply the principles of open and reproducible science;

- Generate and explore hypotheses and research questions for experimental and observational research;

- Select appropriate research designs and methodologies for different research questions;

- Demonstrate critical awareness of the assumptions of these methods and analyses and the limitations associated with experimental and observational research designs;

- Identify the ethical issues involved in experimental and observational research;

- Work as a group to plan and execute a small-scale research project using quantitative research methods;

- Demonstrate critical analysis, evaluation, and synthesis of ideas;

- Use the programming language R to conduct a range of descriptive and inferential statistics.

## Assessments

- **MCQs (5%)**

    - Answer Multiple Choice Questions (MCQs) related to content covered in weeks 1-4 including lectures, data skills sessions, and labs.

- **Data skills portfolio (15%)**

    - Two data skills worksheets using R/RStudio, each worth 7.5%.

- **Stage 1 group report (30%)**

    - Group submission of a planned introduction and method to answer a research question you develop. 
    
 - **Stage 2 individual report (50%)** 
 
    - Individual submission of a reproducible research report containing an abstract, results, and discussion that address the research question you developed in your group. 

Please check the Assessment and Feedback Information Sheet chapters for detailed information and deadlines.

## Course overview

Below is a provisional timetable for this course to show you what we will cover in the lecture, lab, research skills and data skills each week, in addition to where your assessments will be. We will notify you of any changes in advance, but feel free to read ahead to help you plan:

Download this Word file: [PSYCH5088 RM1 Timetable](Supporting/RM1_F2F_Timetable.docx)

**Last updated:** 25/07/2025

## Available support

There is a lot of support in this course to help you build your knowledge and understanding of quantitative research methods and statistics. You do not have to use all the different sources of support, and some will work better for you than others will. Part of learning is about finding what helps you best. Below are a few of the main approaches we have on this course to help you and if in doubt, please just ask:

- Weekly lab sessions with your tutor with time for questions in each lab;

- Graduate Teaching Assistant (GTA) support sessions in-person and online;

- RM1 Teams channel for discussion, questions, and support;

- Student Office Hours (sometimes called Student Drop-in Hours) - just turn up and ask your course leads of lab lead anything;

- Assessment information sheets and common questions and answer documents to support assignments.

The best approach is to write down your questions when they come up, check the available material for answers, and if you are still unsure after that, use one of the approaches above.

However, please note we would ask that you do not send questions, either about a topic or an assignment, as a direct message on Teams to an individual staff member. While we always want to help, this approach is not sustainable and there is a highly likely chance your question will get missed and go unanswered. We would strongly encourage you to post the question on the course Team channel, as that way staff and students have the opportunity to answer your question, and other students can benefit from the answer. Alternatively, use the student office hours or your lab sessions to ask questions more privately.

## GTA data skills support sessions

Building your data skills primarily comes from self-directed learning as you work through the [Fundamentals of Quantitative Research Methods book](https://psyteachr.github.io/quant-fun-v3/){target="_blank"} we have developed. These walk through learning R/RStudio and applying data skills such as wrangling data, visualisation, and inferential statistics. There are also walkthrough videos for most of the chapters and several check-in labs over the semester dedicated to data skills. However, we appreciate you may have questions or encounter errors you cannot work out on your own. That is why we schedule weekly support sessions with our GTAs. 

The GTA support sessions are drop-in sessions, meaning they are not timetabled classes you must attend. They are there to go to if you have a problem, and you can come and ask questions. Our GTAs may demonstrate techniques or how to fix problems, but they are not intended to be chapter walkthroughs. The idea is you engage in self-directed study, and then you can come to the support sessions if you encounter problems. 

Early in the semester, the support sessions have open invites. This means anyone can drop in and there might be a handful of students present and asking questions. However, as we approach key assessment periods, the sessions will have specific sign up slots to ensure the GTAs can provide clearly defined equitable time to each sign-up.  

## Believe in yourself!

Our students have an extremely diverse range of backgrounds, so we assume the knowledge and skills we will help you to learn are new to everybody. The phrase we hear most often is: "everyone else must already know this?!". If you already knew the content, you would not be on this course or programme. Some of you come from a science background while some of you do not, but no one has covered this combination of quantitative research methods in psychology. 

It might be challenging and take some trial and error, but every single one of you *can* do this. Research methods and statistics might not be everyone's favourite course, but it is our job to convince everyone that you *can* do it and it is a critical part of psychology training. 

## Acknowledgements 

We put a lot of effort into creating the resources in this book, but occasionally typos or broken links will slip through. When a student helps us and highlights an error or makes a suggestion, we like to acknowledge it. We would like to thank the following students for helping us:

Yee Lam So.
