```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# MCQ {#MCQ-AIS}

## General information

You must answer a set of multiple-choice questions that relate to the course content covered in weeks 1-4. This includes lectures, data skills, labs, and academic writing tutorials. 

- In total, this assessment is worth 5% of your final course grade. 

- The deadline for submitting the MCQ is **`r MCQ_due`**. 

- The quiz will open one week prior to the deadline, so you can complete the quiz in your own time. However, you must start and finish the quiz in one sitting. Once you start, you **must** finish. 

## How to do well in this assessment

- Keep up with the course content on a weekly basis.

- Complete the essential reading for each lecture.

## Common mistakes

- Not keeping up with the lecture content and reading.

- Failing to read the question carefully.

- Failing to answer all questions. 

## Why am I being assessed like this?

- Testing your knowledge of the course content helps you actively engage with the material, meaning you will learn more.

- Distributed practice is important for learning, so have a few low-stakes assessments early in the course to encourage you to keep up with the content, while being low weighted to reduce the pressure on your overall course grade.

- Engaging with the material on the course will help build a strong foundation for the rest of the RM1 course and your subsequent assessments. 

## Academic Integrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment.

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

- [SRC Advice and Support](https://www.glasgowunisrc.org/advice/){target="_blank"}.

- [Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2024-25/feesandgeneral/studentsupportandconductmatters/reg33/){target="_blank"} and [Plagiarism Statement](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2024-25/feesandgeneral/studentsupportandconductmatters/reg32/){target="_blank"}.

- [Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/enrol/index.php?id=13038){target="_blank"} (a Moodle course you can self-enrol in).

- [Student support for AI, plagiarism, and digital skills ](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"}.

**Statement on groupwork**: We encourage students to form a study group and peer feedback groups. However, this assignment is not a group work assignment, so your work must be your own individual contribution. If you make a study group or a peer review group, avoid sharing your final answers.

## AI Statement

The University of Glasgow recognises the value of generative artificial intelligence tools in academic and professional workplaces. The university has a responsibility to ensure that students acquire the necessary knowledge, skills and other competencies associated within their discipline. The [Student Learning Development](https://www.gla.ac.uk/myglasgow/sld/ai/students/){target="_blank"} service provides general guidance and support for students on the use of generative AI, but each item of assessment in your courses will have specific generative AI guidance about use and misuse in place. Where generative AI restrictions are in place, they have been carefully designed to maximise your learning opportunity whilst discouraging reliance on generative AI in a way that undermines your learning, or development of good professional practice and graduate attributes.

**Statement on use of generative AI**: The current assessment is **summative**, meaning that it contributes to your course grade. The generative AI use for this assessment is categorised as **amber** and use of generative AI is allowed for some tasks during the preparation of the assessment. 

There is no expectation that you will use generative AI and we have no evidence that it's use will confer an advantage for this assessment. The purpose of this assessment is to encourage continuous learning over the semester and check your understanding in a low-stakes assessment. The MCQ has a low course grade percentage to reduce pressure and let you focus on learning. Taking short-cuts now will not provide an accurate overview of your understanding and skill development. 

If you do use generative AI tools, we recommend using it for the following (non-exhaustive) kind of tasks: 

- Clarify complex concepts and reinforce understanding around intended learning outcomes.

- Plan a revision schedule. 

- Generate practice quizzes and questions.

If you do use generative AI tools, we strongly recommend **not** using it for the following (non-exhaustive) kind of tasks: 

- Relying on AI tools for understanding key concepts. 

- Helping you to answer the questions. 

## Feedback information

### How is this assessment graded?

The MCQ has 22 questions with each question being worth 1 point. Your grade will be converted into an alphanumeric grade on the standard 22-point scale (e.g., a score of 16 = B2). 

### What type of feedback will I receive for this assessment?

Once the quiz has closed for all students, you will be able to see which questions you got right and wrong, what the correct answer was, and your overall grade. 

### Who assessed my work?

The MCQ is scored automatically within Moodle. The course leads created and proof read the quiz to ensure the scoring is accurate. 
