```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Stage 1 Group Report {#stage1-AIS}

## General information

The group stage 1 report sets out the introduction (background research, rationale for your study, and your hypothesis where applicable) and planned methods. In your group, you will write about **one** of the two project options on sustainability or belonging. 

- The deadline is **`r stage1_due`**.

- This assessment is worth 30% of your final course grade and will be a group mark. Everyone in your group will receive the same grade and feedback. This means it is important that everyone contributes to the project equitably and agrees on decisions as a group.

- **One member** of your group should submit your complete stage 1 submission to Moodle. This will consist of an introduction and method section that would make up a stage 1 registered report submission prior to collecting data. 

- In this course, you will not be creating or designing the study yourself, just helping to add data to the pool which you will use as the data set to apply your planned analyses to for the final individual stage 2 submission. For further information on the individual stage 2 report, please refer to the [Assessment Information Sheet](#stage2-AIS). 

- You should submit a single Word document (.docx) to Moodle prior to the deadline. The submission link will open at least one week prior to the deadline and will be in the **Assessment: Stage 1 Group and Stage 2 Individual Reports** tab on Moodle.

- As a formative task and to outline ground rules for working in your group, you will complete and submit a [group work agreement](#groupagreement-AIS). We will introduce this document to you in week 2 when you will know your group allocation, but it will involve agreeing to how you will work in and contribute to your group. This will help to plan your assignment and recognise how people may work and interact differently. 

## Word count and formatting

- The maximum word count for this assignment is **`r stage1_words`** words. 

- This includes all text within the introduction and method sections including in-text citations. However, it does not include the references or any appendix items.

 - Please note that there is no 10% rule, **`r stage1_words`** words is a strict upper limit.
 
 - Your work should be presented in a professional sans-serif font, e.g. Arial or Calibri, 12-point font, double-spaced with 1-inch (2.54cm) margins.

 - All citations and references should follow APA 7th edition guidelines.
 
## Type of assessment/structure

- The stage 1 group report is modeled on the first half of a [registered report](https://www.cos.io/initiatives/registered-reports). This is a relatively new type of journal article where the research background, rationale, hypothesis, and planned methods are peer-reviewed prior to conducting a study. Instead of peer-review, your group work will be marked as an assessment. 

- Your stage 1 group report will include an introduction and method section, plus references and appendices (where relevant). You will receive a template outlining the key sections and sub-sections to help with formatting. 

## Assessment Criteria

Your stage 1 group report will be assessed on the three University of Glasgow Intended Learning Outcomes (ILOs), which we split into the following assessment criteria: 

**Quality of the Knowledge and Research**

- Demonstrate theoretical knowledge by providing a detailed evidence-based understanding of the topic of the report.

- Demonstrate technical knowledge by correctly reporting the design, materials, and procedure of the study in the method section.

**Quality of the Evaluation**

- Use and show academic evidence to support all arguments and discussion.

- Evaluate the current literature to provide a clear, evidence-based rationale for your research question and hypothesis (where appropriate).

**Quality of the Academic Communication**

- Write clearly and succinctly with appropriate use of paragraphs, spelling, and grammar.

- Reference all sources and report all information in line with APA guidelines.

- Ensure that all parts of the report have a logical structure, e.g., a broad-to-narrow scope in the introduction, and the method section should be organized into appropriate subheadings. 


## Assessment support

- Guidance on how to complete the stage 1 group report will form part of the weekly course activities, such as content covered in the lectures and labs. 

- We cover the assumptions of simple linear regression (and relatedly, correlations and t-tests) and how to match your statistical model to your design and research question in the lectures and associated reading, such as the relevant sections of the PsyTeachR [Fundamentals of Quantitative Analysis](https://bartlettje.github.io/quant-fun-v3/){target="_blank"} book.

- Further information about assessment criteria and feedback can be found in the [Feedback Information Sheet](#stage1-FIS) section below.

- You can find additional writing and study advice, including 1-to-1 guidance on the [Student Learning Development (SLD) website](https://www.gla.ac.uk/myglasgow/sld/).

## How to do well in this assessment

- Meet each of the assessment criteria; use these as a checklist when you are writing and editing your work.

- Allow time for one or two members of your group to proof-read your work before submission.

- Complete all relevant sections and sub-sections of the stage 1 template to structure your submission.

- Provide an evidence-based rationale for your research question and hypothesis.

- Use the available materials to ensure the accuracy of your decisions.

- Explain your decisions and support them with evidence. Note that there are often multiple decisions you can make and there is not one “right” answer – this is absolutely fine. What matters is that you can explain and support your decisions and it is the sophistication of these explanations that is important.

## Common mistakes

- Not explaining the decisions that you make and not using evidence to support them.

- Writing that is unclear and/or imprecise.

- Inaccuracies in the explanation of planned methodological and statistical information.

- Failure to adhere to the word limit. There is no 10% leeway, we must stop reading when we reach the word count which affects the communication ILO.

## How is the assessment related to the lectures for this course?

The stage 1 report provides you the opportunity to apply many of the concepts you learn in the course materials by collating and synthesising research, and planning your analysis approach based on your research question and design.

## Why am I being assessed like this?

- Registered reports are increasingly common in psychological research and it is a process that will serve you well should you continue with research as it demonstrates a commitment to open and reproducible science.

- The stage 1 report allows you to think through the background and rationale of your research question, and your planned methods and analyses prior to completing the individual stage 2 report.

- The stage 1 report is a group submission to reflect the fact that in most research, these decisions will be made as a team and it allows you to pool your collective knowledge to design the best study possible.

- We follow a scaffolded approach to develop your understanding of writing research reports across the programme. In RM1, you write the introduction and method sections in a group. You then write the results and discussion individually. In RM2 and your dissertation, you work up to writing the full report and dissertation individually. 

## How does this relate to previous work I have completed?

- You can gain informal feedback by talking to your lab tutors, lecturers, and/or by attending student office hours.

- Feedback on any previous written assignment will help with academic communication and using evidence to support your arguments.

## Academic Integrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment.

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

- [SRC Advice and Support](https://www.glasgowunisrc.org/advice/){target="_blank"}.

- [Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg33/){target="_blank"} and [Plagiarism & Academic Integrity Code](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2025-26/feesandgeneral/studentsupportandconductmatters/reg32/){target="_blank"}.

- [Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/enrol/index.php?id=13038){target="_blank"} (a Moodle course you can self-enrol in).

- [Student support for AI, plagiarism, and digital skills ](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"}.

**In summary**:

All work submitted by students for an assessment is accepted on the understanding that it is the student's own effort. This means students’ work should not contain:

- plagiarised content; or

- content that has been produced by another person, website, software or Artificial intelligence (AI) tool (except where AI use is explicitly permitted); or

- content that has been prepared jointly with any other person (except where this is explicitly permitted); or

- content that has already been submitted for assessment by the student at this or any other institution, known as self-plagiarism.

**Statement on groupwork**: This is a group assignment and one person from the group should be nominated to submit the draft and final version of the assignment on Moodle. Your group’s work should not be exactly the same as that of another group in the class, however, as you worked closely in a larger group and from common templates, we know that there may be some unavoidable similarities between team members in the method and results, but it should never be identical or close to identical.

## AI Statement

**University statement on AI**: The University of Glasgow recognises the value of generative artificial intelligence (AI) tools in academic and professional workplaces. The university has a responsibility to ensure that students acquire the necessary knowledge, skills, and other competencies associated within their discipline. The The [Student Learning Development](https://www.gla.ac.uk/myglasgow/sld/ai/students/){target="_blank"} service provides general guidance and support for students on the use of generative AI. Each item of assessment in your courses will have specific guidance about the use of AI. Where generative AI restrictions are in place, they have been carefully designed to maximise your learning opportunity whilst discouraging reliance on generative AI in a way that undermines your learning or development of good professional practice and graduate attributes.

**School statement on AI**: The School of Psychology and Neuroscience recognises that students may choose to explore the use of AI to assist in learning and assessment. We have a responsibility to guide students in the ethical and effective use of AI tools in order to protect their ability to develop subject-specific skills and knowledge. For this reason, we expect that students will:

- Be mindful and transparent about their use of AI, and confident to declare their use of AI so that we can give effective feedback. 

- Respect our guidance on recommended and not recommended use of AI to safeguard their ability to develop as psychologists or neuroscientists.

- Be aware of the risks of using AI (to the environment and to the corpus of human knowledge) and so minimise its use.

- Take personal responsibility for all work they submit for assessment. 

**Statement on use of generative AI**: The current assessment is **summative**, meaning that it contributes to your course grade.  The purpose of this assessment is to provide an opportunity to develop your writing and communication. You can use AI as a learning assistant to help understand lecture content, to give feedback on your work, and to help in finding spelling and grammatical errors. If you want to use translation software (i.e., you write the assignment in another language first) be cautious as the vocabulary and syntax produced by generative AI is not generally in keeping with the current language use and vocabulary in our field and can result in subtle misunderstanding in communication.

Avoid using AI to draft your assignment or structure your work, as these are
specialist skills that you need to practice. Avoid using AI to make your citations or reference section, as there is a risk that it will fabricate information.

There is no expectation that you will use generative AI, and we have no evidence that its use will confer an advantage for this assessment. If you do use generative AI, you **must** acknowledge use in-text via citations and referencing and in an appendix with a declaration of AI use as appropriate. If you choose to use it, we recommend that you use the Microsoft Edge Browser with Copilot and sign in with your university account using the multi-factor authentication to ensure that your work is private and secure. **Please keep a log of your use of AI as we may ask to see this**.

For this assignment, we will consider it a misuse of generative AI if you do not acknowledge using it. Declare all uses of AI, including initial exploration of the subject, literature searching, writing and editing, corrections for grammar and spelling, as well as any other tasks from the course. Be aware that AI may not represent the best response for this task, and you need to take responsibility for everything that is submitted.

::: {.callout-warning}
The references you use and cite in your work are your responsibility, regardless of whether you use generative AI tools or not. Assessments containing hallucinated references that do not exist in peer-reviewed journals may be reported to student conduct.
:::

## Feedback information {#stage1-FIS}

### What type of feedback will I receive for this assessment?

You will receive feedback on your attainment of the overall marking criteria (Knowledge and Research, Critical Evaluation, Academic Communication) in terms of the verbal descriptors from Schedule A and feed forward comments as to how to develop your knowledge and skills for future assignments.

Assessments are graded on the 22-point scale using the Schedule A marking criteria. There are three equally weighted Assessment Criteria (Knowledge and Research, Critical Evaluation, Academic Communication). You can find out more about Schedule A by [downloading this PDF](https://www.gla.ac.uk/media/Media_541792_smxx.pdf) but the important thing to help you interpret your feedback is the use of the verbal descriptors, i.e., the words like “excellent” and “good” used to describe different grades. You should look out for these words to help you understand how you performed on each ILO.

### Can I get more feedback?

You are more than welcome to receive additional feedback after the marking process:

- If you would like to discuss your feedback you should first contact the person that marked your assignment. However, we ask that you wait 24 hours after the release of the feedback before you do so to give you time to fully reflect on the feedback given. 

- When meeting with the person who marked your assignment, you can discuss feedback and how it relates to your overall grade to help you improve in future assignments. However, do not be worried about attending to discuss how to maintain your standard if you have done better than you expected. You are more than welcome to come discuss any aspect of your feedback or the assignment in general. 

- To help any discussion about your feedback, we would ask that you complete the reflection form available on the Moodle page and send that to the person who marked your assignment as part of the discussion, when arranging a meeting.

### How will feedback from this assessment help me in the future?

Primarily, the feedback on this assessment will help support the analysis and write-up of the stage 2 individual report in this course. Additionally, the feedback will help support your qualitative report in RM2, as well as your dissertation and in any future research work you conduct that requires data analysis, decision-making, and evidence-based justification.

### Who assessed my work?

The first marker for your report will be a member of the Research Methods 1 team within the School of Psychology and Neuroscience.

Following University policy, as part of the marking procedures, the assignment marking will be moderated. The moderator will be another member of the research methods team who will moderate a range of work from across the cohort to ensure that appropriate academic standards have been applied in marking the assignments and that they have been applied consistently across the cohort of students being assessed. 

### Can I have my work regraded?

Further feedback meetings with the person who marked your assignment is purely about additional information to help you improve and is not about changing your grade or having your work regraded. That said, even if you are unhappy with your grade, your first point of contact should be to arrange an additional feedback meeting with your marker for further discussion to help explain your feedback and grade. Following this, if you still have concerns you should consult the [guidance from the SRC](https://www.glasgowunisrc.org/advice/academic/appeals/) which provides a clear explanation of the University appeals procedures. 
