lang: en
project:
  type: book
  output-dir: docs
  resources: resources
lightbox: true
execute:
  freeze: auto
book:
  title: MSc Research Methods 1 Course Information
  subtitle: ''
  author:
  - orcid: 0000-0002-4191-5245
    name:
      family: Bartlett
      given: James
  - orcid: 0000-0002-4191-5245
    name:
      family: Paterson
      given: Helena
  - orcid: 0000-0002-4191-5245
    name:
      family: Pham
      given: Thinh
  doi: ''
  license: CC-BY
  description: Key course information for the MSc Research Methods 1 course.
  cover-image: images/logos/logo.png
  image: images/logos/logo.png
  favicon: images/logos/logo.png
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY (2024) Bartlett, Paterson, & Pham
  chapters:
  - index.qmd
  - 01-Course_overview.qmd
  - 02-Resources.qmd
  - part: 03-AIS-00.qmd
    chapters:
      - 03-AIS-01-groupagreement.qmd
      - 03-AIS-02-MCQ.qmd
      - 03-AIS-03-dataskills.qmd
      - 03-AIS-04-stage1.qmd
      - 03-AIS-05-stage2.qmd
  - part: 04-Labs-00.qmd
    chapters:
      - 04-Labs-01.qmd
      - 04-Labs-02.qmd
      - 04-Labs-03.qmd
      - 04-Labs-04.qmd
      - 04-Labs-05.qmd
      - 04-Labs-07.qmd
      - 04-Labs-08.qmd
  - part: 05-Writing-00.qmd
    chapters:
      - 05-Writing-01-MSLQ.qmd
      - 05-Writing-02-Reading.qmd
      - 05-Writing-03-Rationale.qmd
      - 05-Writing-04-Method.qmd
      - 05-Writing-05-power.qmd
      - 05-Writing-06-NHST.qmd
      - 05-Writing-07-Writing.qmd
      - 05-Writing-08-Results1.qmd
      - 05-Writing-09-Results2.qmd
      - 05-Writing-10-Discussion1.qmd
bibliography: include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
