```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Week 4

## Lab overview

This week, we are moving on to the second major section of a report. Keeping the hourglass shape in mind, the method section forms the first narrow part focusing exclusively on your study. The method outlines how you designed your study and follows a standardised series of sub-sections to outline who your participants were, what materials you used, how participants completed your study, and how you approached the data analysis. 

In the lab, we will use an activity to demonstrate principles of reproducibility. After breaking down each sub-section of the method, you will discuss in your groups all the areas containing researcher degrees of freedom to decide on and justify. 

## Tasks to complete prior to your lab

1. Read the [Structure of the Method section](#method-section) research skills chapter. 

2. Complete the [MSLQ study](https://exp.psy.gla.ac.uk/project?SRLproject&guest){target="_blank"} as a participant. This will both help with learning the materials and procedure you will be reporting, and add more data to the pool to analyse. We have posted a screencast of the study on Moodle, so there is no pressure to complete the study as a participant if you do not want to. 

3. You will need a pen/pencil and a piece of paper (or electronic if you have a tablet to draw with) to bring to the lab. 

## Tasks to complete after attending your lab

1. If you have not already allocated tasks, look back at the [stage one task sharing advice](#stageone-planning). Now you know about the method section, think about what details you know about, what you do not know yet, and how you will find out what you do not know. Identify all the researcher degrees of freedom in your method and think about which decisions you can justify. 

2. For inspiration on the writing the method, read the method section (pages 2 and 3) of the article [*Registered Replication Report: Testing Disruptive Effects of Irrelevant Speech on Visual-Spatial Working Memory*](https://jeps.efpsa.org/articles/10.5334/jeps.450){target="_blank"} by Kvetnaya (2018). One component that might feel a little odd is writing the participants section when you do not know the final sample. It might be useful to refer to Kvetnaya's original [stage one version online](https://osf.io/j4475){target="_blank"} to see how she framed the planned sample before the wording changed in the final article. You will also notice the sub-sections are slightly different to what we recommend. 

3. Finalise your rationale, research question, and hypothesis (if applicable) in your group.

## Next week 

After week 4, we have explored both major sections you need for your stage 1 group report. There are still things we do not expect you to know yet, such as the specific statistical test you will need to test your research question, but you will at least know where they go once you have developed this knowledge. So, make sure you discuss in your groups how you plan on splitting tasks now you have a better insight into the method. 

Next week, there will be a pause to the report sections focus in the labs. We will have our first main R focused lab as a check-in. You will complete a pair programming activity to work on wrangling the data extract we shared to help you develop your stage 1 group report. The data you receive for your stage 2 individual report will be in the exact same format, just containing way more participants. Until this point, you will have developed your data wrangling skills in the quant fundamentals books, so we will have a few structured tasks to work on in pairs. 
